# Generated by Django 3.1.1 on 2020-09-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='Web_site',
            field=models.URLField(blank=True, default='', verbose_name='Web site'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='mail_pers',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Personal email'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='mail_pro',
            field=models.EmailField(default='', max_length=254, verbose_name='Professional email'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='mobile_pers',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Personal phone number'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='mobile_pro',
            field=models.CharField(default='', max_length=50, verbose_name='Professional phone number'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='name_first',
            field=models.CharField(default='', max_length=150, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='name_last',
            field=models.CharField(default='', max_length=150, verbose_name='Last name'),
        ),
    ]
