# Generated by Django 3.1.1 on 2020-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0002_auto_20200916_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcard',
            old_name='Web_site',
            new_name='web_site',
        ),
        migrations.AddField(
            model_name='vcard',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='', verbose_name='Web site'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='mobile_pro',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Professional phone number'),
        ),
    ]
