# Generated by Django 3.1.1 on 2020-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0004_auto_20200921_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='organization',
            field=models.CharField(default='', max_length=150, verbose_name='Organization'),
        ),
    ]
