# Generated by Django 3.1.1 on 2020-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0005_auto_20200923_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='', verbose_name='Logo'),
        ),
    ]
