# Generated by Django 3.1.1 on 2020-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0006_auto_20200924_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos/', verbose_name='Logo'),
        ),
    ]
