# Generated by Django 3.1.1 on 2020-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0007_auto_20200924_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos/<django.db.models.fields.CharField>/', verbose_name='Logo'),
        ),
    ]
