# Generated by Django 3.1.1 on 2020-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0008_auto_20200924_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='qr_vcard/logos/%y/%m/', verbose_name='Logo'),
        ),
    ]
