# Generated by Django 3.1.1 on 2020-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0009_auto_20200924_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='qrcode',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='qr_vcard/qrcodes/%Y/%m/', verbose_name='Qr code'),
        ),
        migrations.AddField(
            model_name='vcard',
            name='vcf',
            field=models.FileField(blank=True, db_index=True, null=True, upload_to='qr_vcard/vcf_files/%Y/%m/', verbose_name='Vcard'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, db_index=True, default='', upload_to='qr_vcard/logos/%y/%m/', verbose_name='Logo'),
        ),
    ]
