# Generated by Django 3.1.1 on 2020-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_vcard', '0010_auto_20200928_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='logo',
            field=models.ImageField(blank=True, db_index=True, default='', null=True, upload_to='qr_vcard/logos/%y/%m/', verbose_name='Logo'),
        ),
    ]
